#Soubor:	Makefile
#Autor:		Michal Ormos - 1BIT
#			xormos00@stud.fit.vutbr.cz
#Popis:		makefile pre druhy projekt z ITY

NAME=proj2

all:
	latex $(NAME).tex
	latex $(NAME).tex
	dvips -t a4 $(NAME).dvi
	ps2pdf $(NAME).ps
