#File:		Makefile
#Author:	Michal Ormos - 1BIT
#		xormos00@stud.fit.vutbr.cz
#Description:	Makefile for third ITY project

NAME=proj3

all:
	latex $(NAME).tex
	latex $(NAME).tex
	dvips $(NAME).dvi
	ps2pdf -sPAPERSIZE=a4 $(NAME).ps
