# Makefile - IOS Project 2 - FIT VUT 1BIT
###############################################################
#
# Author:		Michal Orrmos
# E-mail:		xormos00@stud.fit.vutbr.cz
# Date:			15-4-2015
#
###############################################################

CC=gcc
CFLAGS=-std=gnu99 -Wall -Wextra -Werror -pedantic
LFLAGS=-pthread

all:
	$(CC) $(CFLAGS) h2o.c -o h2o $(LFLAGS) 
